/* translation of file "/home/ed/mcsema-testing/llvm-test-suite/MultiSource/Applications/kimwitu++/inputs/f2.k" */
/* generated by:
 *  @(#)$Author: criswell $
 */
#ifndef KC_FUNCTIONS_f2_HEADER
#define KC_FUNCTIONS_f2_HEADER
#include "testk.h"    // in case a user forgets


namespace kc {
void printer (const char *s, uview v);

} // namespace kc

#endif // !  KC_FUNCTIONS_f2_HEADER

