/* translation of file "/home/ed/mcsema-testing/llvm-test-suite/MultiSource/Applications/kimwitu++/inputs/f3.k" */
/* generated by:
 *  @(#)$Author: criswell $
 */
#ifndef KC_FUNCTIONS_f3_HEADER
#define KC_FUNCTIONS_f3_HEADER
#include "testk.h"    // in case a user forgets


namespace kc {

} // namespace kc

#endif // !  KC_FUNCTIONS_f3_HEADER

